### PR TITLE
Web accessibility

### PR DESCRIPTION
**Pull request by Pazzo97**
In this PR I have made some changes to the HTML file.

### **.List all points that I have checked:**

1. Page titles - no issues found
2. Image text alternatives** (alt-text) - gave Images a meaningful alt and removed others from decorations
3. Text headings - Changed the text headings in the middle which had h1 headings
4. Color contrast - no issues found
5. Resize - no issues found
6. Interaction - no issues found
7. Moving content - no issues found
8. Multimedia - no issues found
9. The basic structure of the page - no issues found

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
> -Correction of headings where there were too many h1 headings in the middle of pages. -Provided meaningful alt attributes in order to provide access to information to the users. -Removed alt attributes to the decoration as suggested by my coding partner. -Removed animations that I have merged accidentally from last week's assignment.






 Your report should include:
List all points that you have checked, i.e:
- Page titles
- Image text alternatives** (alt text)
- Text headings
- Color contrast
- Resize
- Interaction
- Moving content
- Multimedia
- The basic structure of the page

#### Each point on the list needs to include the result of your evaluation:
If everything was ok, make a statement about that (e.g. "Page titles - no issues found").



- [ ] Kindly add your report   to the description of your pull request, please do this because this is part of the [project requirements 
](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/6_accessability.md)

**Review by prolajumokeoni — CHANGES_REQUESTED** [review]
Hi Team 👋🏿 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ GitHub flow was correctly used



## Required Changes ♻️

- [ ] Kindly prepare a report listing all points that you have checked, and the result of your evaluation, Check the comment under the review.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Pazzo97** [comment]
Hello @prolajumokeoni ,
Thank you for your review. But I have one question to ask you, should I put that report listing of all points that I have checked that you've mentioned in the Pull Request description?

**Comment by prolajumokeoni** [comment]
> Hello @prolajumokeoni , Thank you for your review. But I have one question to ask you, should I put that report listing of all points that I have checked that you've mentioned in the Pull Request description?

Hi @Pazzo97, yes, please go through the project requirements again 🤗

**Review by mikethreels — APPROVED** [review]
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
